# Generated by Django 4.1 on 2024-01-12 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0002_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(null=True)),
                ("address", models.CharField(max_length=64)),
                ("profile", models.TextField()),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="learn.author"
                    ),
                ),
            ],
        ),
    ]
