# Generated by Django 4.1 on 2024-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0004_course_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("course", models.ManyToManyField(to="learn.course")),
            ],
        ),
    ]
